"""Add memory_state to StoryState

Revision ID: 0c7f115439eb
Revises: 54881faf1508
Create Date: 2026-04-13 11:55:36.707635

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7f115439eb'
down_revision: Union[str, Sequence[str], None] = '54881faf1508'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('story_states', sa.Column('memory_state', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('story_states', 'memory_state')
    # ### end Alembic commands ###
