"""Add language to characters

Revision ID: 1d4b2cacb742
Revises: 0c7f115439eb
Create Date: 2026-04-13 14:46:02.321790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d4b2cacb742'
down_revision: Union[str, Sequence[str], None] = '0c7f115439eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('language', sa.String(), nullable=False, server_default='en'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'language')
    # ### end Alembic commands ###
