"""Add StoryState and StoryEvent

Revision ID: 54881faf1508
Revises: 41edbeeb3771
Create Date: 2026-04-08 15:59:24.797850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54881faf1508'
down_revision: Union[str, Sequence[str], None] = '41edbeeb3771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('story_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('is_major', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_story_events_id'), 'story_events', ['id'], unique=False)
    op.create_table('story_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('current_arc', sa.String(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('objective', sa.String(), nullable=True),
    sa.Column('checkpoint_summary', sa.String(), nullable=True),
    sa.Column('checkpoint_index', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id')
    )
    op.create_index(op.f('ix_story_states_id'), 'story_states', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_story_states_id'), table_name='story_states')
    op.drop_table('story_states')
    op.drop_index(op.f('ix_story_events_id'), table_name='story_events')
    op.drop_table('story_events')
    # ### end Alembic commands ###
